### ISSUE TITLE
Toggle Nav - Push Navigation

### ISSUE THREAD

**Issue by devonash** [anna-trojanowska/center-for-biological-diversity#4]
We want to get this toggle navigation: http://anna-trojanowska.github.io/code-pen-to-sass/ to push to the side. Right now, it's disappeared. I've been trying to make changes in the "toggle-nav" branch. Any suggestions?

@tiffanytse
@thomasjbradley

**Comment by thomasjbradley** [comment]
It looks like it's because jQuery isn't loading.

Here on this line of code, `src` is spelled wrong:
https://github.com/anna-trojanowska/center-for-biological-diversity/blob/gh-pages/_layouts/default.html#L24

**Comment by anna-trojanowska** [comment]
That fixed it.
