### ISSUE TITLE
Closing nav and getting the nav to work on mobile

### ISSUE THREAD

**Issue by anna-trojanowska** [anna-trojanowska/center-for-biological-diversity#5]
@thomasjbradley

Hey! 

I'm having a hard time figuring out how to make the "x" button close the navigation. Do I need to add js to make it work or can the action be reversed a simpler way? 

Also, I don't understand why the toggle menu icon now disappears when the site is mobile since I never touched the code that effects it. 

Sorry to bug you on the weekend, I'll understand if you can't help! 

<img width="972" alt="screen shot 2016-03-05 at 2 50 03 pm" src="https://cloud.githubusercontent.com/assets/6340298/13550023/ab3e10c8-e2e1-11e5-9c08-4ada483e9a5e.png">
<img width="400" alt="screen shot 2016-03-05 at 2 50 18 pm" src="https://cloud.githubusercontent.com/assets/6340298/13550024/ab3e3a6c-e2e1-11e5-994e-9137037635bb.png">

**Comment by thomasjbradley** [comment]
_For the "x":_ Yeah, you're going to need some Javascript to make it work.

---

I don't know exactly what happened to the navigation but it looks like it's just never visible.
Here, its always set to `display: none`, outside a media query:
https://github.com/anna-trojanowska/center-for-biological-diversity/blob/gh-pages/scss/components/_header.scss#L5-L13

**Comment by anna-trojanowska** [comment]
This was happening because I had a closing bracket in the wrong place in a media query and I think i changed the display: none, too. Solved that, but have yet to add the javascript to the toggle.
