### ISSUE TITLE
Added new content page and navigation does not work

### ISSUE THREAD

**Issue by anna-trojanowska** [anna-trojanowska/center-for-biological-diversity#6]
@thomasjbradley

One more thing, I linked one of Steve's pages to the navigation but when I am on that page, the navigation does not work. 

His page uses the default layout so it should work, right?

<img width="795" alt="screen shot 2016-03-05 at 2 54 54 pm" src="https://cloud.githubusercontent.com/assets/6340298/13550050/421ba866-e2e2-11e5-9883-a57722ee62ca.png">

**Comment by thomasjbradley** [comment]
The `{{site.baseurl}}` is missing in the `<script>` tag:
https://github.com/anna-trojanowska/center-for-biological-diversity/blob/gh-pages/_layouts/default.html#L30

**Comment by anna-trojanowska** [comment]
Yep that did it! Thank you :) @thomasjbradley
